### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by Paizo** [ibm-messaging/mq-jms-spring#100]
Hello,

in this project readme in the section:

Related documentation
[MQ documentation](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_latest) -> the link appear to hit a non existent page. Can you please fix it with the correct url?
thanks

**Comment by ibmmqmet** [comment]
Thanks for pointing that out. I'll fix links in the next release. Unfortunately, auto checkers for broken links don't work too well with those documentation sites because they are still resolved/redirected to a real page. Can't look for 404s.

**Comment by mcordeiro73** [comment]
I'm seeing the same issue for the link under Additional Properties to the Knowledge Center. Any chance you can post the correct links to this issue in the meantime?

**Comment by ibmmqmet** [comment]
All links should now work
