### ISSUE TITLE
How to configure the output directory for log files?

### ISSUE THREAD

**Issue by sw-tracker** [ibm-messaging/mq-jms-spring#103]
When an error occurs, I see log files stored on the top level folder of my spring boot application. I would like to be able to configure this, so that all log files get stored in a folder that I can gitignore. How can I configure this using spring boot properties?

- ibmmq-jms-spring 
```
        <dependency>
            <groupId>com.ibm.mq</groupId>
            <artifactId>mq-jms-spring-boot-starter</artifactId>
            <version>3.0.2</version>
        </dependency>
```
- Java version 17.

The log files are called something like `mqjms.log.0`, etc.

**Comment by ibmmqmet** [comment]
There's no specific Spring Boot property. 

But this is how you set it for any Java program: https://www.ibm.com/docs/en/ibm-mq/9.3?topic=problems-logging-errors-mq-classes-jms
