### ISSUE TITLE
Replace org.json with com.github.openjson in com.ibm.mq.jakarta.client

### ISSUE THREAD

**Issue by NicklasWallgren** [ibm-messaging/mq-jms-spring#107]
The [original library](http://www.json.org/) is [licensed under a standard BSD license with an additional line that requires the use of the software only for "non-evil" purposes](http://www.json.org/license.html). Since this is ill-defined, many downstream consumers of this software find this license condition unacceptable. The moral is don't put jokes into legal documents. More background information is collected by the Debian team members at https://wiki.debian.org/qa.debian.org/jsonevil

https://github.com/openjson/openjson

**Comment by ibmmqmet** [comment]
This is not something that can be handled through this repository. If you've got a suggested change to the underlying MQ client libraries, then you can open an Idea at https://integration-development.ideas.ibm.com

**Comment by NicklasWallgren** [comment]
> This is not something that can be handled through this repository. If you've got a suggested change to the underlying MQ client libraries, then you can open an Idea at https://integration-development.ideas.ibm.com

Alright - thank you for pointing me in the right direction!
