### ISSUE TITLE
Support for CachingConnectionFactory

### ISSUE THREAD

**Issue by tlabossa** [ibm-messaging/mq-jms-spring#11]
It would be nice if it support CachingConnectionFactory or something pooling mehanism.

Now I can not wrap ConnectionFactory to CachingConnectionFactory in simple @Configuration file becouse circular dependency and encounter other jmsAutoConfig healt etc.

Simular like this https://github.com/spring-projects/spring-boot/issues/12161

Thank you!

**Comment by mballoni** [comment]
What kind of circular dependency are you referring to?
 Would you mind to provide an failing application example? 

 I'm looking into the possibility of creating a PR.

Thanks

**Comment by mballoni** [comment]
I've made a PR with the pooled connection factory:

https://github.com/ibm-messaging/mq-jms-spring/pull/12

**Comment by tlabossa** [comment]
Thank you very much!
