### ISSUE TITLE
Not able to set send time out for this IBM MQ

### ISSUE THREAD

**Issue by Arav3299** [ibm-messaging/mq-jms-spring#113]
Hi All,

I am integrating IBM MQ in my application and when deploying in the production due to load and high TPS, this library taking a while to drop a message in the MQ and it is blocking the real time request. Can someone suggest how can I set send timeout using this library or if any?

**Comment by ibmmqmet** [comment]
There's no MQ JMS timeout for simply sending messages. There are configurable timers that can help with noticing dead connections, but that doesn't sound relevant here.

So you might choose to do the messaging work in a separate thread so as not to block other activity.

And make sure you're not doing implicit MQCONNs for each send, as establishing a client connection can be much slower than other operations.  So use cached connectionfactories for example.
