### ISSUE TITLE
connection issue with spring boot 3

### ISSUE THREAD

**Issue by birbirsbirbirs** [ibm-messaging/mq-jms-spring#114]
'org.springframework.boot' version '3.3.4'
java 21
com.ibm.mq:mq-jms-spring-boot-starter:3.3.3'
error log:  Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').

ibm broker in docker server: docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 \
           --publish 1414:1414 \
           --publish 9443:9443 \
           --detach \
           ibmcom/mq

similar to application in "s1" directory

**Comment by birbirsbirbirs** [comment]
[cmq.zip](https://github.com/user-attachments/files/17103492/cmq.zip)

**Comment by chughts** [comment]
When you run the IBM MQ container you must supply

- MQ_APP_PASSWORD
- MQ_ADMIN_PASSWORD

You can also supply

- MQ_APP_USER
- MQ_ADMIN_USER

See https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-containers/ for guidance.

**Comment by birbirsbirbirs** [comment]
with following properties in application.yml, it worked. thank you very  very much.
`ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd`

**Comment by birbirsbirbirs** [comment]
`docker run --env LICENSE=accept --env MQ_QMGR_NAME=QM1 --volume qm1data:/mnt/mqm --publish 1414:1414 --publish 9443:9443 --detach --env MQ_APP_USER=app --env MQ_APP_PASSWORD=passw0rd --env MQ_ADMIN_USER=admin --env MQ_ADMIN_PASSWORD=passw0rd --name QM1 icr.io/ibm-messaging/mq:latest
`
