### ISSUE TITLE
Support to Java 7?

### ISSUE THREAD

**Issue by Menighin** [ibm-messaging/mq-jms-spring#19]
I'm trying to use this with  `WebLogic 12.1.3` running on Java 7.
When deploying the application I get the following error:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.15.RELEASE)
<Dec 11, 2018 4:41:26 PM BRST> <Error> <Class Loaders> <BEA-2162500> <Class, com.ibm.mq.spring.boot.MQConfigurationProperties, was compiled with an incompatible version of Java. Make sure that all the classes needed by the application have been compiled with a compatible java version. java.lang.UnsupportedClassVersionError: com/ibm/mq/spring/boot/MQConfigurationProperties : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/ibm/mq/spring/boot/MQConfigurationProperties : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at weblogic.utils.classloaders.GenericClassLoader.defineClass(GenericClassLoader.java:412)
        at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:366)
        Truncated. see log file for complete stacktrace
>
```

I'm on `Spring Boot 1.5.15.RELEASE` and using `com.ibm.mq:mq-jms-spring-boot-starter:0.0.4`.

I'm guessing this is because the package was built using Java 8.. If so, is there a version built with Java 7? Any suggestions on how I could proceed? Thanks!

**Comment by ibmmqmet** [comment]
The downloads on maven central include the source files so you could try to recompile this library from the older levels. 

Java 7 ended normal life several years ago, and the JRE shipped with the MQ libraries that this is wrapping is Java 8, so it didn't seem to be a particular priority to use the obsolete version. And Spring itself has the Java 8 prereq these days.

**Comment by Menighin** [comment]
Hi guys, thanks for the answers.
I will try to use the `all client jar` and configure the beans myself, as suggested.
I tried building the lib with Java 7 but got some errors... I think it will be faster to just use the all-client.

@ibmmqmet, I think it would make sense in older versions, like 0.0.4 which is the compatible one with Spring 1.5, to be compatible with Java 7, since spring boot 1.5 itself is. But that ship has sailed long ago and I do agree people shouldn't be using Java 7 these days... But well, my client has this pre-requisite, so...

Thanks!

**Comment by Menighin** [comment]
Guys I'm sorry for reoping this...
Just maybe you guys could help a fellow developer. I'm trying @edwingsm suggestion. I 'm using `com.ibm.mq.allclient:9.1.1.0` and I have set the properties for the queue right. Thing is I'm getting the following error:

```
2018-12-12 10:38:14.009 ERROR 23952 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'QL.TEST' - retrying using FixedBackOff{interval=5000, currentAttempts=64, maxAttempts=unlimited}. Cause: JMSFMQ6312: An exception occurred in the Java(tm) MQI.; nested exception is com.ibm.mq.jmqi.JmqiException: CC=2;RC=2495;AMQ8568: The native JNI library 'mqjbnd64' was not found. For a client installation this is expected. [3=mqjbnd64]
```

For what I understand, this error is because there is a lib missing in the queue, right?
The queue is not implemented locally and I do not have a way to access it. All I know is that it is using Websphere MQ 7.1 (yes, old :/). Do you guys have any clue on what can I do to fix this?

**Comment by ibmmqmet** [comment]
Looks like you need at minimum to set the WMQ_CONNECTION_MODE property on the CF to say that the connection is to a remote queue manager rather than local. See the MQConnectionFactoryFactory file in this repo for an example of the properties you may need.

**Comment by Menighin** [comment]
Thanks for the tip @ibmmqmet.
I tried setting but got the same error. This is how I'm setting it (using Kotlin btw):

```
@bean 
open fun websphereConnectionFactory(): ConnectionFactory {
        val connectionFactory = MQQueueConnectionFactory()
	connectionFactory.queueManager = "QUEUE_MANAGER"
	connectionFactory.channel = "CHANNEL_NAME"
	connectionFactory.hostName = "HOST_IP"
	connectionFactory.port = 1414
	connectionFactory.transportType = 0
	connectionFactory.setIntProperty(WMQConstants.WMQ_CONNECTION_MODE, WMQConstants.WMQ_CM_CLIENT);

	return MQQueueConnectionFactory()
}
```

And I'm using simply like:
```
@JmsListener(destination = "QUEUE_NAME", containerFactory = "websphereConnectionFactory")
fun onReceive(message: Message<Any>) {
	log.warn("Received Message: ${message.payload}")
}
```

Do you see anything missing there....?

**Comment by edwingsm** [comment]
This is how i defined the connection factory

 ```
@Bean
    public ConnectionFactory jmsCachingConnectionFactory() throws JMSException {
        ConnectionFactory connectionFactory = mqConnectionFactory();
        UserCredentialsConnectionFactoryAdapter connectionFactoryAdapter = new UserCredentialsConnectionFactoryAdapter();
        connectionFactoryAdapter.setTargetConnectionFactory(connectionFactory);
        connectionFactoryAdapter.setUsername(mqUser);
        return new CachingConnectionFactory(connectionFactoryAdapter);
    }

    private MQConnectionFactory mqConnectionFactory() throws JMSException {
        // disable log file
        System.setProperty("com.ibm.msg.client.commonservices.log.status", "OFF");
        MQConnectionFactory mqConnectionFactory = new MQConnectionFactory();
	mqConnectionFactory.setHostName(hostAndPort[0]);
	mqConnectionFactory.setPort(Integer.parseInt(hostAndPort[1]));
        mqConnectionFactory.setQueueManager(mqManagerName);
        mqConnectionFactory.setChannel(mqChannelName);
        mqConnectionFactory.setTransportType(WMQConstants.WMQ_CM_CLIENT);
        return mqConnectionFactory;
    }

    @Bean
    public JmsTemplate jmsQueueTemplate(ConnectionFactory jmsCachingConnectionFactory) throws JMSException {
        JmsTemplate jmsTemplate = new JmsTemplate();
        jmsTemplate.setConnectionFactory(jmsCachingConnectionFactory);
        jmsTemplate.setDestinationResolver(new DynamicDestinationResolver());
        jmsTemplate.setPubSubDomain(false);
        return jmsTemplate;
    }
```

**Comment by Menighin** [comment]
Guys, thank you so much.
Turned out the problem was with my clients Websphere. Its working now with my code above!
