### ISSUE TITLE
Topic destinations are not working

### ISSUE THREAD

**Issue by james-r-smith** [ibm-messaging/mq-jms-spring#22]
Queue connections are working fantastic with this library, but I have topics that I need to connect to, which are not working. Required information for ticket is listed below.

* Java version : `1.8`

* MQ JMS Spring Boot Starter Version :
```xml
<dependency>
    <groupId>com.ibm.mq</groupId>
    <artifactId>mq-jms-spring-boot-starter</artifactId>
    <version>2.1.1</version>
</dependency>
```

* Small code sample :

```java
@Component
public class JMSListener {
    // Tested with both `/` format and `.` format
    @JmsListener(destination = "TEST/TOPIC")
    public void onMessage(final String message) {
        log.info(message);
    }
}
```

* Exception :
```
Setup of JMS message listener invoker failed for destination 'TEST/TOPIC' - trying to recover. Cause: JMSWMQ2008: Failed to open MQ queue 'TEST/TOPIC'.; nested exception is com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2085' ('MQRC_UNKNOWN_OBJECT_NAME').
```

**Comment by ibmmqmet** [comment]
From the Spring documentation: 
> By default, Spring Boot creates a JmsTemplate configured to transmit to queues by having pubSubDomain set to false. The JmsMessageListenerContainer is also configured the same. To override, set spring.jms.isPubSubDomain=true via Boot’s property settings (either inside application.properties or by environment variable). 

And see, for example, https://stackoverflow.com/questions/30291067/jmslistener-usage-for-publish-subscribe-topic which shows another way to set the pubsub domain via the connection factory

**Comment by james-r-smith** [comment]
Yes, that's correct. Thanks for the help, @ibmmqmet. 😊👍

```java
@Configuration
@EnableJms
public class JMSContext {
    @Bean
    public JmsListenerContainerFactory<?> topicFactory(ConnectionFactory connectionFactory,
                                                       DefaultJmsListenerContainerFactoryConfigurer configurer) {
        DefaultJmsListenerContainerFactory factory = new DefaultJmsListenerContainerFactory();
        // This provides all boot's default to this factory, including the message converter
        configurer.configure(factory, connectionFactory);
        // You could still override some of Boot's default if necessary.
        factory.setPubSubDomain(true);
        return factory;
    }
}
```

**Comment by JakesIV** [comment]
I just want to know if it would be possible to consume MQEvent format (PCF messages) using this API. I did try and keep on getting this error "MQJE001: Completion Code '2', Reason '3013'." which according the big Google is because JMS do not support the additional MQ headers. I have used the method described here to convert the byte message to PCF. https://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q128400_.htm

I saw this discussion but I had conclusion.
http://www.mqseries.net/phpBB2/viewtopic.php?t=71804

Could you please help and if you also ask why one want to process PCF message in JMS the answer is simple to process MQ event messages to push to ELK stack

**Comment by ibmmqmet** [comment]
See https://www.ibm.com/developerworks/community/blogs/messaging/entry/PCF_Processing_in_JMS_a_gotcha_and_the_solution?lang=en

**Comment by denisorlov** [comment]
> ```java
> // Tested with both `/` format and `.` format
>     @JmsListener(destination = "TEST/TOPIC")
> ```

What is this formats, could you explain please?
How to use DEV.BASE.TOPIC mq-container
- topic name: DEV.BASE.TOPIC
- topic string: dev/

I receive
JMSCC1112 | The operation for a domain specific object was not valid. The operation ''createTopic'' is not valid for type ''QueueSession''.
