### ISSUE TITLE
Spring IBM MQ support Backout Queues

### ISSUE THREAD

**Issue by mykhailomoskura** [ibm-messaging/mq-jms-spring#25]
IBM Wepshere MQ supports functionalityfor putting message to BackoutQueue.
Is it implemented mq-jms-spring  ?
- ibmmq-jms-spring  2.1.0
- Java 8

**Comment by ibmmqmet** [comment]
Handling of backout queue is done automatically within the MQ JMS classes. There's nothing extra to do in wrappers like Spring.

**Comment by mykhailomoskura** [comment]
Hi
Would it put message to backout queue 
on @Transactional rollback using jmsTemplate when queue is full?

**Comment by ibmmqmet** [comment]
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q032280_.htm

As I said before, this is handled by the MQ JMS classes.
