### ISSUE TITLE
Large number of sessions when using transactions

### ISSUE THREAD

**Issue by psloan** [ibm-messaging/mq-jms-spring#29]
Hi,

Not sure if you can help with this issue. We are using the current (2.1.2) version of the spring boot starter and experience an issue where the number of SVRCONN channel instances doubles when we change to transaction mode. We are using the spring cache and the Spring frameworks DefaultMessageListenerContainer.  

It does seem to be an known issue when using Camel to invoke SpringBoot over JMS.  We see two issues:
1) the Spring logic limits JMS to one connection, therefore we can't use CCDT queue manager groups to load balance multiple connections across different queue managers.
2) the way Camel Interacts with spring under transaction mode appears to cause the spring framework to create a new channel instance for the session and essentially leave the existing instance associated with the session orphaned. 

Any clever ideas on how we can specify 4 concurrentConsumer sessions in Camel and actually get 4 JMS session instances (and open handles on the queue) instead of 8 JMS sessions and 1 connection for a total of 9 channel instances?  

Thanks in advance.

**Comment by ibmmqmet** [comment]
Sorry, I've no idea about how Camel operates. You might be able to do something with connection pooling. google suggests that using the camel-sjms component is an alternative that might help some situations as it removes the Spring aspect (and the need for this package!) but that's the only advice I've got.

**Comment by psloan** [comment]
Sadly it looks like camel-sjms doesn't support XA which we need. "Support for Customizable Transaction Commit Strategies (Local JMS Transactions only)" means we need to stay with the cable-jms component which relies on the Spring Transaction Manager to work its XA magic. 

I guess with XA we need to code a bean with its independent connection factory for each queue manager connection just like Jeff did in issue 7 here: https://github.com/ibm-messaging/mq-jms-spring/issues/7 

We are not really sure why the transacted mode makes Spring use one orphaned and one real session for each of the Camel concurrentSessions we specify but it seems like there is no way around the behaviour is you use the Spring framework in transaction mode.

**Comment by ibmmqmet** [comment]
Advice/discussion happened on mqseries.net. Closing here as nothing more to be done.
