### ISSUE TITLE
Allow USER_AUTHENTICATION_MQCSP to be configured from properties.

### ISSUE THREAD

**Issue by moskanz** [ibm-messaging/mq-jms-spring#3]
It would be usefull in some cases

**Comment by ibmmqmet** [comment]
The code does set that flag when a userid and password have been configured. Is there any specific reason why you'd want to have it independently configurable?

**Comment by moskanz** [comment]
Flag is hardcoded to true, but in my environment authentication is not working with this value for some reason. Maybe it is missconfiguration in my mq. But when i set flag to false, everything working fine. I guess that having default value to true is right way, but it is usefull to be able to change it by config property.

**Comment by moskanz** [comment]
@ibmmqmet Is it possible to update package on mvnrepository.com? Does it require to bump version?

**Comment by martinscheffler** [comment]
Hi, I had the same issue. +1 for updating maven package. Thanks for the cool work btw, keeps a lot of boilerplate code out of my project :)
