### ISSUE TITLE
TLS/certificate authentication not working if user/password is not set to null

### ISSUE THREAD

**Issue by kervoaz** [ibm-messaging/mq-jms-spring#30]
- ibmmq-jms-spring :2.1.2
- Java version : oracle 1.8

Hello,
This issue looks like the closed issue "Empty/Blank passwords don't seem to work. #18".
If we use certificate as authentication mechnanism, properties user and password (ibm.mq.user /ibm.mq.password) must be set to null in properties file. If these properties are not declared in prop file, they are setup with dummy values(admin/passw0rd) which overwrite the certif authentication mechanism.
This behavior should be at least described in the documentation(if it is the expected behavior).
From my side, I have lost many time because in properties file, I have commented these 2 properties instead of define at null...:(

Thnaks
Regards

**Comment by ibmmqmet** [comment]
The README already mentions these properties to avoid password checking: 

> These attributes can be set to an empty value, to use the local OS userid automatically with no authentication (if the queue manager has been set up to allow that).

but I'll see if there's a reasonable way to further highlight it

**Comment by ibmmqmet** [comment]
README further updated in 2.2.0 release
