### ISSUE TITLE
Unable to configure multiple MQ Managers

### ISSUE THREAD

**Issue by anandbabud1987** [ibm-messaging/mq-jms-spring#33]
Please include the following information in your ticket.

- ibmmq-jms-spring version(s) : 1.5.15
- Java version (including vendor and platform). 1.8 Openjdk
- A small code sample that demonstrates the issue.

I am struggling to configure more than one mq manager . Is there a way to configure multiple MQ managers using spring boot mq jms? Thanks.

**Comment by ibmmqmet** [comment]
See #7 for some approaches people have used

**Comment by ibmmqmet** [comment]
Closing as dup
