### ISSUE TITLE
CCDT as JSON

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-jms-spring#40]
Does this code base support CCDT file in JSON format?   MQ client 9.2.0 supports this format.

**Comment by ibmmqmet** [comment]
This package has nothing to do with the CCDT file parsing - it's entirely done by the underlying client implementation based on configuration like the URI pointing at it. (And there's no 9.2.0 at the moment - I guess you meant 9.1.2.0.) 

It does look like the allclient.jar that's currently available on Maven Central may not imbed or explicitly name the JSON library needed so you might need to have that separately named in the app's build control, like **pom.xm**l if you get ClassNotFoundException or similar. The required artifact is "**org.json:json**".
