### ISSUE TITLE
Does this dependency provide Asynchronous consuming message from queue

### ISSUE THREAD

**Issue by ishwarps** [ibm-messaging/mq-jms-spring#41]
HI,
I need to integrate spring with IBM MQ.  i need to consume the message asynchronous from Queue and topic.
i was searching the example but i did not found where its showing consuming/reading message asynchronous from queue.
does  "mq-jms-spring" dependency provides the asynchronous and thread safe like how EJB MDB  working?

**Comment by ibmmqmet** [comment]
The actual asynchronous consumption is handled by Spring classes that in turn make use of this module. See for example the @JmsListener annotation.

**Comment by ishwarps** [comment]
@ibmmqmet : Thanks for response.  if you have some sample code or reference . could share the link.

**Comment by ishwarps** [comment]
@ibmmqmet : Thanks for update.i got it .
