### ISSUE TITLE
Use @Configuration(proxyBeanMethods=false) wherever possible?

### ISSUE THREAD

**Issue by PascalSchumacher** [ibm-messaging/mq-jms-spring#45]
What do you think about using ´@Configuration(proxyBeanMethods=false)´ instead of `@Configuration` to avoid the (potentially expensive) generation of cglib proxies?

See: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html#proxyBeanMethods-- and: https://github.com/spring-projects/spring-boot/issues/9068 for details.

By the way: Thank you very much for providing mq-jms-spring. 👍

**Comment by ibmmqmet** [comment]
Looks like it should work - I don't see anywhere that there's a breaking reason. And it's been done for some of the other components that have similar design patterns, so I'll look to make that change next time I do some updates.

**Comment by PascalSchumacher** [comment]
> I'll look to make that change next time I do some updates.

Thank you very much! Looking forward to it.

**Comment by ibmmqmet** [comment]
Done in 2.2,5

**Comment by PascalSchumacher** [comment]
Thank you very much! 👍
