### ISSUE TITLE
ccdtUrl as a file

### ISSUE THREAD

**Issue by lafual** [ibm-messaging/mq-jms-spring#46]
Using Spring Boot version 2.2.2, if I use 

`
ibm.mq.ccdtUrl=file:////path/file.tab
`

The tab is not is not found even though it exists. Even if I mis-name the file I do not get an error. Only removing the `file://` causes an error with respect to file location.

If I define the `MQQueueConnectionFactory` as a `@Bean` then do;

`
MQQueueConnectionFactory mqcf = new MQQueueConnectionFactory();
mqcf.setCCDTURL(new URL('file:////path/file.tab'));
`

It works and also errors if the file is not found. Shouldn't this work or MUST the property be an HTTP or FTP URL?

**Comment by ibmmqmet** [comment]
Using a file: url seems to work fine for me. Including getting errors if the file does not exist or if the file does not have a definition to point at the qmgr. I used the sample1 program from this repo along with modifications to the application.properties file to try it out.

**Comment by lafual** [comment]
I misread the errors;

`
ibm.mq.ccdtUrl=file:////path/wrongName.tab -- 2278 MQRC_CLIENT_CONN_ERROR
ibm.mq.ccdtUrl=file:////path/correctName.tab -- 2035 MQRC_NOT_AUTHORIZED
`

But it works using the `@Bean` code above with the correct file and same JKS using -D

Also in Spring Tool Suite 4, the YML auto-complete give `ccdt-url`, not `ccdtUrl`, but the same tests for both parameters, give the same result.

**Comment by ibmmqmet** [comment]
Spring Boot allows various syntax forms for properties, including dashes, underscored and mixedCase and ALL UPPER as  different external ways of specifying properties have different preferred formats. They all map to the same option inside the configuration components.

If you print the entire stack trace, MQRC_CLIENT_CONN_ERROR would show more detailed errors such as file not found.

And for MQRC_NOT_AUTHORIZED make sure you've understood the README on the default userid/password properties that are applied and how they can be changed or bypassed.

**Comment by lafual** [comment]
In other words RTFM :-)

As per the README, defining `ibm.mq.user=` (i.e. to nothing), fixed the problem.

Thanks for your time and patience!
