### ISSUE TITLE
Authentication failure , The specified userid is not used on connections

### ISSUE THREAD

**Issue by JakesIV** [ibm-messaging/mq-jms-spring#48]
Please include the following information in your ticket.

- ibmmq-jms-spring version(s) :2.2.4
- Java version 
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
Windows
- Properties
ibm.mq.queueManager=QMNAME
ibm.mq.channel=SPRINGBOOT.SVRCONN
ibm.mq.connName=tservername(1415)
ibm.mq.user=USERID
ibm.mq.password=password

@JmsListener(destination = "HUB.SPRINGBOOT.SND")
    public void onAuditMessage(final Message receivedMessage) {
	if (receivedMessage instanceof BytesMessage) {
	    BytesMessage bytesMessage = (BytesMessage) receivedMessage;
	    byte[] bytesreceived;
	    try {
		bytesreceived = new byte[(int) bytesMessage.getBodyLength()];
		bytesMessage.readBytes(bytesreceived);
		MQMessage mqMsg = new MQMessage();
		mqMsg.write(bytesreceived);
		mqMsg.encoding = receivedMessage.getIntProperty(WMQConstants.JMS_IBM_ENCODING);
		mqMsg.format = receivedMessage.getStringProperty(WMQConstants.JMS_IBM_FORMAT);
		String codePage = receivedMessage.getStringProperty(WMQConstants.JMS_IBM_CHARACTER_SET);

		mqMsg.seek(0);
		log.info("message len " + Integer.toString(mqMsg.getMessageLength()));
		log.info("message encoding " + Integer.toString(mqMsg.encoding));
		log.info("message format " + mqMsg.format);
		log.info("message type " + Integer.toString(mqMsg.messageType));
		log.info("message code page " + codePage);

		try {
		    log.info("message content:  " + mqMsg.readStringOfByteLength(mqMsg.getMessageLength()));
		} catch (Exception e) {
		    log.info("No message content : " + e.getMessage());
		}

	    } catch (JMSException e) {
		e.printStackTrace();
	    } catch (IOException e) {
		e.printStackTrace();
	    }
	} else if (receivedMessage instanceof TextMessage) {
	    TextMessage txtMessage = (TextMessage) receivedMessage;
	    log.info("Text message received");
	    try {
		log.info(txtMessage.getText());
	    } catch (JMSException e) {
		e.printStackTrace();
	    }
	} else {
	    log.info("Not valid message format");
	    log.info(receivedMessage.getClass().getName());
	    log.info("================");
	}

    }

Error received
Could not refresh JMS Connection for destination 'HUB.SPRINGBOOT.SND' - retrying using FixedBackOff{interval=5000, currentAttempts=0, maxAttempts=unlimited}. Cause: JMSWMQ2013: The security authentication was not valid that was supplied for queue manager 'QMNAME' with connection mode 'Client' and host name 'SERVERNAME(1415)'.; nested exception is com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').

When looking at the logs it is trying to authoirse using the userid the app is running on and not the one specified in the properties file.
what are we doing wrong???

**Comment by ibmmqmet** [comment]
What is the exact message in the qmgr error log? You say it's "trying to authorise" but you also write "authentication" failure in the issue title. I suspect you don't have the ADOPTCTX value set on the AUTHINFO object on the qmgr so that the authentication of the specified userid is OK and it's failing later on the authorisation phase. 
See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.sec.doc/q113250_.htm

**Comment by ibmmqmet** [comment]
Closing as no recent updates
