### ISSUE TITLE
MQAutoConfiguration property condition

### ISSUE THREAD

**Issue by zsenyeg** [ibm-messaging/mq-jms-spring#49]
Hey,

com.ibm.mq.spring.boot.MQAutoConfiguration auto configuration depends on spring.jta.enabled spring property. Auto configuration is not working if spring.jta.enabled is false.

Can you help me to understand this property dependency? Why this autoconfiguration is bound to jta?

- ibmmq-jms-spring version: 2.1.2
- spring boot version: 2.2.0.RELEASE
- Java version: Oracle 1.8, RHEL

```
@Configuration
@ConditionalOnProperty(
    prefix = "spring.jta",
    value = {"enabled"},
    matchIfMissing = true
)
@AutoConfigureBefore({JmsAutoConfiguration.class})
@AutoConfigureAfter({JndiConnectionFactoryAutoConfiguration.class, JtaAutoConfiguration.class})
@ConditionalOnClass({ConnectionFactory.class, MQConnectionFactory.class})
@ConditionalOnMissingBean({ConnectionFactory.class})
@EnableConfigurationProperties({MQConfigurationProperties.class, JmsProperties.class})
@Import({MQXAConnectionFactoryConfiguration.class, MQConnectionFactoryConfiguration.class})
public class MQAutoConfiguration {
    public MQAutoConfiguration() {
    }
}
```

Cheers,
zsenyeg

**Comment by ibmmqmet** [comment]
There doesn't seem to be a good reason for that check on the property. Perhaps there was some time ago, but it doesn't appear to be needed now at any rate. I'll remove that check next time I update the package.
