### ISSUE TITLE
Add support for all MQConnectionFactory properties

### ISSUE THREAD

**Issue by adzubla** [ibm-messaging/mq-jms-spring#50]
I need to configure XMSC_WMQ_TEMPORARY_MODEL and can't do it using "ibm.mq.*" properties. I used the code below but it is very cumbersome...

    @Bean
    public DefaultJmsListenerContainerFactory myFactory(DefaultJmsListenerContainerFactoryConfigurer configurer, ConnectionFactory connectionFactory) throws JMSException {
        DefaultJmsListenerContainerFactory factory = new DefaultJmsListenerContainerFactory();
        configurer.configure(factory, connectionFactory);

        MQConnectionFactory cf = ((MQConnectionFactory) connectionFactory);
        cf.setStringProperty(WMQConstants.WMQ_TEMPORARY_MODEL, "DEV.APP.MODEL.QUEUE");

        return factory;
    }

It would be great if *all* MQConnectionFactory properties could be set using mq-jms-spring confgurator.

**Comment by ibmmqmet** [comment]
Using a configurer method as you have done is the right way for additional properties to be provided on the CF. 

There are many possible properties allowed on a CF, a lot of which are very rarely (or, these days, never) used. I don't want to add all of them as it would make the code much more cluttered with no real benefit.

See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.javadoc.doc/WMQJMSClasses/com/ibm/mq/jms/MQConnectionFactory.ConnectionFactoryProperty.html
for a huge list of potential properties.

I'll take a look to see if there are a small number of additional properties that might be worth doing. Alternatively, I have accepted (and will continue to accept) PRs from people who had specific properties that they were interested in and who were able to update the code.

**Comment by adzubla** [comment]
The configurer approach has one significant drawback... I'm using Spring Cloud and the connectionFactory is wrapped by `org.springframework.cloud.sleuth.instrument.messaging.LazyTopicConnectionFactory` and the real MQConnectionFactory can't be accessed.

It could be like Spring Kafka, that supports generic properties using the prefix `spring.kafka.consumer.properties` like the example below (from https://docs.spring.io/spring-kafka/reference/html/#tips-n-tricks)

    spring.kafka.consumer.properties.isolation.level=read_committed

So, I could write

    ibm.mq.properties.WMQ_TEMPORARY_MODEL=DEV.APP.MODEL.QUEUE

It would solve all problems related to mq properties (old and new). Only the most popular ones should be explicitly declared by the framework.

**Comment by ibmmqmet** [comment]
Available in v2.2.6
