### ISSUE TITLE
JMSCC0020: This session is closed when stopping a spring boot application

### ISSUE THREAD

**Issue by mleguevel** [ibm-messaging/mq-jms-spring#52]
Hello, 
We have an error displayed in the logs when stopping a spring boot application that uses this lib.

Here is the required information:
- version affected by this issue: **2.2.5**
- Java version: **AdoptOpenJDK 11, tested on docker and on Red Hat**

Here is the stacktrace: 

```
185658 [DefaultMessageListenerContainer-1] WARN  o.m.pooled.jms.JmsPoolSession - Caught exception trying close() when putting session back into the pool, will invalidate. com.ibm.msg.client.jms.DetailedIllegalStateException: JMSCC0020: This session is closed.
An application called a method that must not be used after the session is closed.
Ensure that the session is not closed before calling the method.
com.ibm.msg.client.jms.DetailedIllegalStateException: JMSCC0020: This session is closed.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.ibm.msg.client.commonservices.j2se.NLSServices.createException(NLSServices.java:319)
        at com.ibm.msg.client.commonservices.nls.NLSServices.createException(NLSServices.java:226)
        at com.ibm.msg.client.jms.internal.JmsErrorUtils.createException(JmsErrorUtils.java:126)
        at com.ibm.msg.client.jms.internal.State.checkNotClosed(State.java:142)
        at com.ibm.msg.client.jms.internal.JmsSessionImpl.checkNotClosed(JmsSessionImpl.java:3040)
        at com.ibm.msg.client.jms.internal.JmsSessionImpl.setMessageListener(JmsSessionImpl.java:2161)
        at com.ibm.mq.jms.MQSession.setMessageListener(MQSession.java:978)
        at org.messaginghub.pooled.jms.JmsPoolSession.close(JmsPoolSession.java:91)
        at org.springframework.jms.support.JmsUtils.closeSession(JmsUtils.java:109)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.clearResources(DefaultMessageListenerContainer.java:1241)
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1128)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The issue can be reproduced with this simple pom:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.5.RELEASE</version>
    </parent>

    <groupId>com.test</groupId>
    <artifactId>mq-spring-boot-error</artifactId>
    <version>4.0.0</version>

    <dependencies>
        <dependency>
            <groupId>com.ibm.mq</groupId>
            <artifactId>mq-jms-spring-boot-starter</artifactId>
            <version>2.2.5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <executable>true</executable>
                </configuration>
            </plugin>
        </plugins>

    </build>

</project>
```

The following class:

```java
@SpringBootApplication
@EnableJms
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @JmsListener(destination = "queueName")
    public void listener(Message message) {
        System.out.println("Message received");
    }
}
```

And a minimal configuration that includes `ibm.mq.pool.enabled = true`

This happens when starting and stopping the application with systemd via the executable generated by spring boot (or by simply running something like `MODE=service ./my-app.jar start` and `kill $PID`).

It seems to be due to the fact that spring first closes the JMS sessions by calling `JmsPoolConnectionFactory.stop` and then it destroys the `AbstractJmsListeningContainer` which leads to calling JmsPoolSession.close which calls JmsSessionImpl.setMessageListener and in this function, the code checks that the session is alive.

I hope it's clear.

Thank you.

**Comment by ibmmqmet** [comment]
I don't know that there's anything that can be done in this package - as you say, it seems to be in the way the core Spring code interacts with the pooling library. You might be better off asking in the full Spring repository. Though I suspect that the Spring recommendation would be to move to using the Spring Cache options instead.

And having said that, there are a number of times I see errors/FDCs coming from the MQ client code when unexpectedly stopped eg "kill <pid>" (nothing to do with spring or pools) so getting errors during a shutdown should not be completely unexpected.

**Comment by mleguevel** [comment]
Hello @ibmmqmet, 
Thank you for your reply. You're right, not sure anything can be done in this package.

> as you say, it seems to be in the way the core Spring code interacts with the pooling library. You might be better off asking in the full Spring repository. Though I suspect that the Spring recommendation would be to move to using the Spring Cache options instead.

My personal impression is that it's not really "spring's fault". I think the problem comes either from the pooling library calling `setMessageListener(null)` (there might be a good reason do that though) or from the ibm mq client checking the state of the session when setting a message listener (same, there might a good reason to do that).

As for spring recommendations, I think I saw in the docs that they do recommend the pooling library that you're using.

Thank you.

**Comment by ibmmqmet** [comment]
Closing as not really a problem for this repo.
