### ISSUE TITLE
Trying to connect

### ISSUE THREAD

**Issue by soteras** [ibm-messaging/mq-jms-spring#56]
Please include the following information in your ticket.

I'm trying to connect but I received the error bellow

IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2393' ('MQRC_SSL_INITIALIZATION_ERROR').

- ibmmq-jms-spring version(s) that are affected by this issue.
1.3.72

- Java version (including vendor and platform).
openjdk 11.0.8 2020-07-14

- A small code sample that demonstrates the issue.

**Comment by ibmmqmet** [comment]
There are a lot of reasons for that error code. There's often something in the error logs (AMQERR*.LOG) on either the client or qmgr side that can give more information. Most common reasons include
* local keystore not accessible
* certificate (or signing cert from CA) not in partner's keystore
* invalid/non-matching cipherspec between partners

**Comment by ibmmqmet** [comment]
closing as no further updates
