### ISSUE TITLE
Fixed Backoff settings configuration

### ISSUE THREAD

**Issue by satyab4** [ibm-messaging/mq-jms-spring#58]
Hi,
I am using mq-jms-spring-boot-starter 2.3.0 version. Is there a way to configure FixedBackOff through yml properties along with other MQ Connection properties.

Thanks
Satya

**Comment by ibmmqmet** [comment]
That's not controlled by the MQ code, but would be managed by the spring JMS listener classes. From a quick scan of the Boot source, it doesn't look like Spring have exposed that through an auto-configuration option for the listeners though it is in the main Spring Framework configurations. 

See `back-off` and `recovery-interval` options in https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/jms.html 

You might be better off to ask in one of the core Spring Boot channels as that value would apply to all JMS providers not just MQ.

**Comment by ibmmqmet** [comment]
closing as a core Spring Boot/Framework matter
