### ISSUE TITLE
Set JmsConstants.JMS_IBM_MQMD_APPLIDENTITYDATA

### ISSUE THREAD

**Issue by tradefinsup** [ibm-messaging/mq-jms-spring#59]
Hello,
is it possible to set the JmsConstants.JMS_IBM_MQMD_APPLIDENTITYDATA with the spring sample?
I tried to set it with
 setStringProperty("JMS_IBM_MQMD_ApplIdentityData","MyValue");
but it does not work.
Thanks,
Frank

**Comment by ibmmqmet** [comment]
Yes it can be done, but it's a bit convoluted. 

The key thing to know is how MQ JMS permits you to set all the fields in the MQMD in contravention of the JMS spec. See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.dev.doc/q032330_.htm It requires you to set properties on both the message and the destination.

Getting to the destination properties with Spring requires additional work. If you're using the simplest application code today, you're probably using the JmsTemplate class. So you need to intercept its creation of the destination object:
```
jmsTemplate.setDestinationResolver(new Resolver());
```
where Resolver is a class that implements the required interface:
```
public class Resolver implements DestinationResolver {

  @Override
  public Destination resolveDestinationName(Session session, String destinationName, boolean pubSubDomain) throws JMSException {
    Destination d = null;
    d = session.createQueue(destinationName);
    MQQueue q = (MQQueue)d;
    q.setBooleanProperty(WMQConstants.WMQ_MQMD_WRITE_ENABLED, true);
    q.setIntProperty(WMQConstants.WMQ_MQMD_MESSAGE_CONTEXT, WMQConstants.WMQ_MDCTX_SET_ALL_CONTEXT);   
    return d;
  }
}
```
Finally, you can set the properties on the message
```
 jmsTemplate.convertAndSend(qName, o, msg -> {
        msg.setStringProperty(WMQConstants.JMS_IBM_MQMD_APPLIDENTITYDATA, "MyApplIdData");
        return msg;
      });
```

**Comment by tradefinsup** [comment]
Thanks, it works!
