### ISSUE TITLE
Sample to demonstrate JmsPoolConnectionFactoryProperties use and best practices with jmsTemplate.

### ISSUE THREAD

**Issue by mdvalenza** [ibm-messaging/mq-jms-spring#60]
In your MQConnectionProperties class you are just using default settings for JmsPoolConnectionFactoryProperties , it would be a great improvement if you showed how to change these settings and leverage JMSTemplate in a way that shows connection pooling working.
- ibmmq-jms-spring version(s) that are affected by this issue.
All

This is not really an issue with the code but an idea for improvement.  Or maybe links to Spring JMSTemplate examples that have more advanced pooling examples, would also be helpful in the read me section describing pooling properties.

**Comment by ibmmqmet** [comment]
I can add a link to the documentation for these properties from the underlying project. But the preferred mechanism in Spring these days appears to be the spring.jms.cache properties - the PooledJMS works but Spring seem to push people to use the cache interface instead. I'll add some more words to that effect to the README too.

**Comment by mdvalenza** [comment]
Noticed when adding DEBUG logging to Spring Boot application.properties file that I can see Spring.JMS but not anything for IBM for example:
logging.level.org.springframework.jms=DEBUG
logging.level.com.ibm.mq=DEBUG
does the IBM code use a different logger?

**Comment by ibmmqmet** [comment]
The MQ Spring Boot code participates in the Spring logger framework though there's not a lot logged (just 1 error case I can see right now). The MQ JMS libraries have their own tracing enablement. See for example https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.tro.doc/q031860_.htm

**Comment by ibmmqmet** [comment]
README updated for the 2.4.0 release
