### ISSUE TITLE
spring framework 5.3.1 (spring-boot 2.4.0)

### ISSUE THREAD

**Issue by bence0726** [ibm-messaging/mq-jms-spring#63]
Please include the following information in your ticket.

- ibmmq-jms-spring version(s) that are affected by this issue : **2.3.5**
- Java version (including vendor and platform). : **11**
- A small code sample that demonstrates the issue. **-**

Hello,
I would like to ask you a question about spring-boot and spring framework version updates.
Can I expect it in the near future, that this starter will be updated to depend on spring framework 5.3.x  instead of 5.2.x? So, basically a spring-boot upgrade to 2.4.0?
I really want to use spring-boot 2.4.0 which already relies on springframework 5.3, but your starter is so convenient that I don't want to throw it away in the same time. However, during spring-boot 2.4 startup the SpringApplication.run() already calls such methods that only exist in spring-context 5.3.1

If not, what do you thing? Can I simply use it with spring-context:5.3.1 with explicitly forcing maven to pull that, instead of 5.2.10-RELEASE?

**Comment by ibmmqmet** [comment]
Updating to 2.4/5.3 is something I am planning to do. I want to do it alongside a couple of other things that are not quite ready yet, so it'll be perhaps a week or so before I can release it. 

You might be able to force maven to pull in 2.4/5.3 explicitly with an appropriate `<dependencyManagement>` block in pom.xml to override the nested version but it's not something I've tried with this package.

**Comment by bence0726** [comment]
Okey, really cool!
Thank you for your almost instant response!

I'll be waiting for this upgrade.
Have a nice day!

**Comment by ibmmqmet** [comment]
Released version 2.4.0 this morning now that MQ 9.2.1 is also available
