### ISSUE TITLE
Does this library provide out-of-the-box metrics/statistics?

### ISSUE THREAD

**Issue by mdiass** [ibm-messaging/mq-jms-spring#64]
Hi everyone!

I would like to know if this library (mq-jms-spring) provides any out-of-the-box metrics/statistics (for example, using Micrometer counter, gauges and timers) about the messages sent and received.

Thanks in advance!

**Comment by ibmmqmet** [comment]
There's nothing in this specific library, which primarily implements the mechanisms to connect to the queue manager, before getting out of the way and letting the Spring JMS (or core JMS APIs) do the actual message work.  

The queue manager to which the application connects can produce a whole load of statistics and other monitoring information at various levels. Depending on what you are looking for, then those might be appropriate.

For metrics generated directly out of application code, that's something I'd consider to fit more naturally at the common Spring Framework JMS layer as things like counts of puts/gets would be generic for all JMS providers. I don't think it is currently implemented in the Spring Framework either, but that's where enhancement requests would more likely fit.

**Comment by mdiass** [comment]
> 
> 
> There's nothing in this specific library, which primarily implements the mechanisms to connect to the queue manager, before getting out of the way and letting the Spring JMS (or core JMS APIs) do the actual message work.
> 
> The queue manager to which the application connects can produce a whole load of statistics and other monitoring information at various levels. Depending on what you are looking for, then those might be appropriate.
> 
> For metrics generated directly out of application code, that's something I'd consider to fit more naturally at the common Spring Framework JMS layer as things like counts of puts/gets would be generic for all JMS providers. I don't think it is currently implemented in the Spring Framework either, but that's where enhancement requests would more likely fit.

Thanks @ibmmqmet for the explanation!
