### ISSUE TITLE
Question: Running the Spring Boot Listener in HA Mode

### ISSUE THREAD

**Issue by sandeep540** [ibm-messaging/mq-jms-spring#66]
Hi 
Wanted to check on how to run the Spring Boot listener in HA Mode? is it possible? How to make sure each message is processed once by on the listeners

<img width="1020" alt="Screen Shot 2021-01-11 at 10 34 33 AM" src="https://user-images.githubusercontent.com/741952/104210718-cd856b80-53f8-11eb-9770-8c9b91fb3366.png">
Please include the following information in your ticket.

**Comment by ibmmqmet** [comment]
Don't really understand what you are asking. Each MQ message will always be destructively retrieved by only a single consumer from a particular queue, though it's not guaranteed on WHICH instance of a consumer would get it. That's a fundamental rule of MQ behaviour.

If you're asking about other aspects of messaging or connectivity, for example pub/sub topologies then you need to be a lot clearer in the question.

**Comment by ibmmqmet** [comment]
No update received.
