### ISSUE TITLE
How to configure Primary and Secondary queue

### ISSUE THREAD

**Issue by damvinod** [ibm-messaging/mq-jms-spring#69]
We have HA setup of IBM MQ. So as a client I need to connect to Primary and Secondary queue. So how to do it in application.properties

**Comment by ibmmqmet** [comment]
Simplest way is to use a comma-separated list of addresses in the conname. See [the KC](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=commands-define-channel#q085520___conname). Or do the equivalent in the CCDT.

**Comment by ibmmqmet** [comment]
closing as answered
