### ISSUE TITLE
Code moved to another repository?

### ISSUE THREAD

**Issue by PascalSchumacher** [ibm-messaging/mq-jms-spring#77]
The latest `mq-jms-spring-boot-starter` version in maven central is `2.6.2`, but this repository does not seem to contain the code for this. Was the source code moved to another repository?

**Comment by ibmmqmet** [comment]
No, I just got interrupted after sending to maven, and then had some vacation time. Should be up to date now.

**Comment by PascalSchumacher** [comment]
Thanks! 👍
