### ISSUE TITLE
Please Upgrade 'mq-jms-spring-boot-starter' to Use Spring Boot 2.7.0

### ISSUE THREAD

**Issue by BenjaminNeale-Heritage** [ibm-messaging/mq-jms-spring#84]
Hi,

Spring Boot 2.7.0 was released a few weeks ago.  We are planning to upgrade to SB 2.7.0 but are concerned about potential dependency conflicts ince the 'mq-jms-spring-boot-starter' is still using SB 2.6.7.  Can you please update to SB 2.7.0 in the 'mq-jms-spring-boot-starter'?
https://spring.io/blog/2022/05/19/spring-boot-2-7-0-available-now

Thanks,
Ben

**Comment by ibmmqmet** [comment]
My plan is to release a new version to coincide with the release of MQ 9.3 towards the end of this month. That looks like it also matches to Boot 2.7.1's date. 

There's a bunch of related infrastructure changes I've been making that made it tricky to do an interim update.

**Comment by BenjaminNeale-Heritage** [comment]
Makes sense. Thanks for the update. 🙂

**Comment by ibmmqmet** [comment]
2.7.1 now available based on MQ9.3 and Spring Boot 2.7.1

Also a 0.3.0-M3 version to work with Jakarta-based environments. See https://marketaylor.synology.me/?p=1236

**Comment by BenjaminNeale-Heritage** [comment]
Thanks @ibmmqmet
