### ISSUE TITLE
Autoconfigure Micrometer connection metrics like Rabbit MQ does

### ISSUE THREAD

**Issue by desprez** [ibm-messaging/mq-jms-spring#89]
Hello
great job for this : it's very usefull.

I want to know if it possible to add some connections metrics in MQAutoConfiguration like RabitMQ does :

https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/amqp/RabbitMetricsAutoConfiguration.java

https://github.com/rabbitmq/rabbitmq-jms-client/blob/main/src/main/java/com/rabbitmq/jms/admin/RMQConnectionFactory.java

**Comment by ibmmqmet** [comment]
The queue manager already produces a whole load of metrics including connection request counts. That's not something I'd expect to then also have in a specific client library with yet another way to interrogate it. There are many tools available to collect and display those queue manager metrics - see for example the `amqsrua` sample program, the Grafana interfaces [here](https://github.com/ibm-messaging/mq-metric-samples), the documented Accounting and Statistics events ...
